apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap-app.yaml
  - secret-db.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - app-service.yaml
  - app-deployment.yaml
  - app-route.yaml
  - init-job.yaml
  - rbac-access.yaml
commonLabels:
  app.kubernetes.io/managed-by: gitops
images:
  - name: harbor.skyr.dca.scc/gitops/customer-web
    newTag: 0.1.0
  - name: harbor.skyr.dca.scc/gitops/customer-db-init
    newTag: 0.1.0
  - name: harbor.skyr.dca.scc/gitops/postgresql-15
    newTag: latest
