apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: gitops-demo
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: ocp-gitops-demo
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: ocp-gitops-demo
    spec:
      containers:
        - name: postgres
          image: registry.redhat.io/rhel9/postgresql-15:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: POSTGRESQL_DATABASE
              value: customers
            - name: POSTGRESQL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_SUPERPASS
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/pgsql/data
      securityContext:
        fsGroup: 26
        runAsUser: 26
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteMany"]
        storageClassName: ocs-storagecluster-cephfs
        resources:
          requests:
            storage: 5Gi
