# Centralized RBAC definitions for GitOps demo operators.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-argocd-controller
  namespace: gitops-demo
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager
  namespace: gitops-demo
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-demoscc-secrets
  namespace: gitops-demo
subjects:
  - kind: User
    name: demoscc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cosign-secret-manager
  namespace: openshift-gitops
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-demoscc-cosign-secret
  namespace: openshift-gitops
subjects:
  - kind: User
    name: demoscc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cosign-secret-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-configmap-manager
  namespace: openshift-pipelines
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-demoscc-tekton-configmaps
  namespace: openshift-pipelines
subjects:
  - kind: User
    name: demoscc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-configmap-manager
