apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-demoscc-cosign-secret
  namespace: openshift-gitops
subjects:
  - kind: User
    name: demoscc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cosign-secret-manager
