apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-demoscc-secrets
  namespace: gitops-demo
subjects:
  - kind: User
    name: demoscc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-manager
