apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: gitops-demo
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: ocp-gitops-demo
    app.kubernetes.io/component: database
stringData:
  DB_USER: customer
  DB_PASSWORD: customer
  DB_SUPERUSER: postgres
  DB_SUPERPASS: changeme
