apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: airgap-
resources:
  - ../../base
images:
  - name: quay.io/example/ocp-gitops-demo-app
    newName: registry.airgap.local/gitops/customer-web
    newTag: 0.1.0
  - name: quay.io/example/ocp-gitops-demo-db-init
    newName: registry.airgap.local/gitops/customer-db-init
    newTag: 0.1.0
  - name: registry.redhat.io/rhel9/postgresql-15
    newName: registry.airgap.local/rhel9/postgresql-15
    newTag: 1-80
patches:
  - target:
      kind: Job
      name: seed-customers
    patch: |
      - op: replace
        path: /spec/backoffLimit
        value: 3
  - target:
      kind: Deployment
      name: customer-web
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: APP_ENV
          value: airgap
