apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: airgap-
resources:
  - ../../base
patches:
  - target:
      kind: Job
      name: seed-customers
    patch: |
      - op: replace
        path: /spec/backoffLimit
        value: 3
  - target:
      kind: Deployment
      name: customer-web
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: APP_ENV
            value: airgap
